name: Build docker and push to artifactory repo
description: perform a build and tag and push to a desired repo. Artifactory secrets should be set.

inputs:
  docker_context_directory:
    type: string
    description: The directory to work in
    default: .
  image_name:
    type: string
    description: The name of the image to build
    required: true
  image_tag:
    type: string
    description: The docker image tag
    required: true
  artifactory_username:
    type: string
    description: The Artifactory username
    required: true
  artifactory_password:
    type: string
    description: The Artifactory password
    required: true
  artifactory_repo:
    type: string
    description: The Artifactory repository to push the image to
    required: true
  artifactory_image_path:
    type: string
    description: The path in the Artifactory repository to push the image to
    required: true
  build_dockerfile:
    type: string
    description: The path to the Dockerfile to build
  docker_target:
    type: string
    description: The build stage target to build in the Dockerfile. Optional will build final stage by default.
  docker_build_args:
    type: string
    description: The build arguments to pass to the Dockerfile. Pipe separated list of key=value pairs.
runs:
  using: composite

  steps:
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Artifactory
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.artifactory_repo }}
        username: ${{ inputs.artifactory_username }}
        password: ${{ inputs.artifactory_password }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup Image Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ inputs.artifactory_repo }}/${{ inputs.artifactory_image_path }}/${{ inputs.image_name }}
        tags: |
          type=raw,value=${{ inputs.image_tag }}

    - name: Build and Push Image to artifactory.io
      uses: docker/build-push-action@v6
      with:
        push: true
        context: ${{ inputs.docker_context_directory }}
        file: ${{ inputs.build_dockerfile || 'Dockerfile' }}
        build-args: ${{ inputs.docker_build_args }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        # Docker build target refers to the build stage in the docker files
        # requiring a value here will make the shareable action difficult to use.
        # Ommitting the target will build the final stage by default.
        # https://docs.docker.com/get-started/docker-concepts/building-images/multi-stage-builds/#:~:text=In%20your%20multi,stage%20by%20default.
        target: ${{ inputs.docker_target }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
