version: "3.4"
services:

  web:
    image: scv-web
    environment:
      - API_URL=${API_URL}
      - IpFilterRules=${IpFilterRules}
      - RealIpFrom=${RealIpFrom}
      - WEB_BASE_HREF=${WEB_BASE_HREF}
    ports:
      - 8080:8080
    depends_on:
      - api

  api:
    image: scv-api
    environment: 
      - FileServicesClient__Username=${FileServicesClientUsername}
      - FileServicesClient__Password=${FileServicesClientPassword}
      - FileServicesClient__Url=${FileServicesClientUrl}
      - LookupServicesClient__Username=${LookupServicesClientUsername}
      - LookupServicesClient__Password=${LookupServicesClientPassword}
      - LookupServicesClient__Url=${LookupServicesClientUrl}
      - LocationServicesClient__Username=${LocationServicesClientUsername}
      - LocationServicesClient__Password=${LocationServicesClientPassword}
      - LocationServicesClient__Url=${LocationServicesClientUrl}
      - Request__ApplicationCd=${RequestApplicationCd}
      - Request__AgencyIdentifierId=${RequestAgencyIdentifierId}
      - Request__PartId=${RequestPartId}
      - WebBaseHref=${WEB_BASE_HREF}
    ports:
      - 5000:5000