name: Schema-Spy

on:
  workflow_dispatch:
env:
  IMAGE_NAME: schema-spy
  WORKING_DIRECTORY: ./
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Schema Spy Repo
        id: gitops
        uses: actions/checkout@v4
        with:
          repository: bcgov/SchemaSpy.git
          ref: master

      - name: Docker Build Backup Image and push to Artifactory
        uses: ./.github/workflows/actions/docker-build-push-artifactory
        with:
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: latest
          artifactory_repo: ${{ env.ARTIFACTORY_REPO }}
          artifactory_image_path: ${{ env.ARTIFACTORY_IMAGE_PATH }}
          build_dockerfile: ${{ env.BUILD_DOCKERFILE }}
