name: Web

on:
  workflow_dispatch:
env:
  IMAGE_NAME: web
  IMAGE_TAG_PREFIX: dev
  WORKING_DIRECTORY: ./
  GITOPS_BRANCH: develop
  GITOPS_LICENCE_PLATE: b3c707
  ARTIFACTORY_REPO: artifacts.developer.gov.bc.ca
  ARTIFACTORY_IMAGE_PATH: sbc3-images
  BUILD_DOCKERFILE: api/Dockerfile.release
jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get short SHA
        id: short_sha
        run: |
          echo "::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)"
          echo "Short SHA: $SHORT_SHA"

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Docker Build Image
        run: |
          docker build --tag ${{ env.IMAGE_NAME }} -f ${{ BUILD_DOCKERFILE }} . 
          docker tag ${{ env.IMAGE_NAME }} ${{ ARTIFACTORY_REPO }}/${{ ARTIFACTORY_IMAGE_PATH }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_PREFIX }}-${{ steps.short_sha.outputs.SHORT_SHA }}
          docker push ${{ ARTIFACTORY_REPO }}/${{ ARTIFACTORY_IMAGE_PATH }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_PREFIX }}-${{ steps.short_sha.outputs.SHORT_SHA }}

      - name: Update ArgoCD Repo
        uses: ./.github/workflows/actions/update-argo-repo
        with:
          licence_plate: ${{ env.GITOPS_LICENCE_PLATE }}
          gitops_branch: ${{ env.GITOPS_BRANCH }}
          image_tag: ${{ env.IMAGE_TAG_PREFIX }}-${{ steps.short_sha.outputs.SHORT_SHA }}
          helm_property: /webtag
          helm_paths: "web/values.yaml ../develop/values.yaml"
